<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aaa030a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c64221c0a0c48656c6c6f52657175657374120c0a046e616d65180120" .
            "012809221d0a0a48656c6c6f5265706c79120f0a076d6573736167651801" .
            "20012809328c020a0747726565746572123e0a0853617948656c6c6f1218" .
            "2e68656c6c6f776f726c642e48656c6c6f526571756573741a162e68656c" .
            "6c6f776f726c642e48656c6c6f5265706c792200123d0a05536179486912" .
            "182e68656c6c6f776f726c642e48656c6c6f526571756573741a162e6865" .
            "6c6c6f776f726c642e48656c6c6f5265706c7922003001123f0a07536179" .
            "42616c6112182e68656c6c6f776f726c642e48656c6c6f52657175657374" .
            "1a162e68656c6c6f776f726c642e48656c6c6f5265706c79220028011241" .
            "0a074469736375737312182e68656c6c6f776f726c642e48656c6c6f5265" .
            "71756573741a162e68656c6c6f776f726c642e48656c6c6f5265706c7922" .
            "002801300142360a1b696f2e677270632e6578616d706c65732e68656c6c" .
            "6f776f726c64420f48656c6c6f576f726c6450726f746f5001a20203484c" .
            "57620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

